#!/usr/bin/env node
/**
 * Russian documentation freshness tracker.
 *
 * This repository carries a third documentation locale (`*.ru.md` sibling
 * files) layered beside the upstream English/Simplified-Chinese pairing
 * corpus. The upstream `verify-translation-pairing` gate knows nothing about
 * `.ru.md` files by design, so this script owns the Russian layer's own
 * contract:
 *
 * 1. Every in-scope English document MAY have a `foo.ru.md` sibling; missing
 *    translations are reported as the remaining work queue, never an error.
 * 2. Every pair that exists MUST be confirmed consistent: the manifest at
 *    `scripts/russian-docs/manifest.json` records the git blob hash of each
 *    side at the last confirmation. Editing either side without re-recording
 *    marks the pair `outdated`.
 * 3. Every existing pair MUST mirror the source structurally: heading-depth
 *    sequence and the verbatim fenced-code-block sequence (info string and
 *    body, byte-for-byte) match the English side.
 *
 * Scope mirrors the upstream Chinese pairing scope: every Markdown document
 * outside dependency/build trees, minus the files the Chinese contract
 * excludes (read from `scripts/translation-pairing.manifest.json`), minus
 * instruction symlinks (`CLAUDE.md`), frozen archived Agent Notes, and legal
 * license disclosures.
 *
 * Usage (plain Node, zero dependencies):
 *   node scripts/russian-docs/check.mjs                 # status + validation
 *   node scripts/russian-docs/check.mjs --list          # one line per pair
 *   node scripts/russian-docs/check.mjs --write <p...>  # re-confirm pairs
 *   node scripts/russian-docs/check.mjs --strict        # exit 1 on outdated,
 *                                                       # unrecorded, orphan
 *
 * A pair argument names any of its three paths or the bare stem, resolved
 * against the repository root. `--write` stores the CURRENT contents' hashes;
 * run it only after checking the two sides say the same thing.
 */

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { join, relative, dirname, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const MANIFEST_PATH = join(ROOT, 'scripts', 'russian-docs', 'manifest.json')
const EXCLUSIONS_PATH = join(ROOT, 'scripts', 'translation-pairing.manifest.json')

const SKIP_DIRS = new Set([
  '.git', '.github', 'node_modules', 'vendor', 'lib', 'dist', '.generated',
  '.cache', '.dist', '.dsh-build', 'coverage', '.venv',
])
// Agent Notes are internal bilingual (EN/ZH) engineering decision records; the
// Russian layer deliberately covers user-facing documents only.
const SKIP_DIR_PREFIXES = ['.agents/notes', '.agents/skills']
const SKIP_FILES = new Set([
  'THIRD_PARTY_NOTICES.md',
  // Generated catalogs are regenerated by scripts/gen-*.ts; their Russian
  // twins are hand-maintained static translations, so a regeneration shows up
  // as an ordinary outdated pair instead of silently dropping translations.
  'docs/tool-catalog.md',
  'docs/config-catalog.md',
  'docs/persistence-catalog.md',
  'docs/graph-atlas.md',
  'docs/module-graph.md',
  'docs/event-producer-consumer.md',
  // Meta-documentation of the translation process itself.
  'docs/i18n/README.md',
  'docs/i18n/translation-rules.md',
  'scripts/fixtures/translation-prompt/snapshot-note.md',
])
const SKIP_BASENAMES = new Set(['AGENTS.md', 'AGENTS.canonical.md'])
// Test snapshots/fixtures are model-visible expected outputs replayed
// byte-exact by the suite; they must never carry a Russian twin.
function isTestArtifact(rel) {
  return rel.includes('/tests/snapshots/') || rel.includes('/tests/fixtures/')
}

// SKILL.md bodies are instructions consumed by agents, not by humans.
function isSkillBody(rel) {
  const base = rel.split('/').pop()
  return base.startsWith('SKILL') && rel.includes('/skills/')
}

const args = process.argv.slice(2)
const strict = args.includes('--strict')
const listOnly = args.includes('--list')
const writeIndex = args.indexOf('--write')
const writePairs = writeIndex === -1 ? null : args.slice(writeIndex + 1)

function walk(dir, base, out) {
  let entries
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    return out
  }
  for (const entry of entries) {
    const abs = join(dir, entry.name)
    const rel = relative(base, abs).split(sep).join('/')
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) walk(abs, base, out)
      continue
    }
    out.push(rel)
  }
  return out
}

function gitBlobHash(content) {
  const buffer = Buffer.from(content, 'utf8')
  return createHash('sha1').update(`blob ${buffer.length}\0`).update(buffer).digest('hex')
}

/** Heading-depth sequence, e.g. [1, 2, 3, 3]. */
function headingDepths(text) {
  return [...text.matchAll(/^#{1,6} /gm)].map(match => match[0].length - 1)
}

/** Ordered fenced-code-block signatures: info string plus byte-exact body. */
function fenceSignatures(text) {
  const lines = text.split('\n')
  const signatures = []
  let open = null // { marker, info, body }
  for (const line of lines) {
    const match = open === null ? /^ {0,3}(`{3,}|~{3,})\s*(.*)$/.exec(line) : null
    if (match) {
      open = { marker: match[1], info: match[2].trim(), body: [] }
      continue
    }
    if (open !== null) {
      const close = new RegExp(`^ {0,3}${open.marker[0]}{${open.marker.length},}\\s*$`)
      if (close.test(line)) {
        signatures.push(`${open.info}\n${open.body.join('\n')}`)
        open = null
      } else {
        open.body.push(line)
      }
    }
  }
  return signatures
}

function loadExclusions() {
  if (!existsSync(EXCLUSIONS_PATH)) return []
  return JSON.parse(readFileSync(EXCLUSIONS_PATH, 'utf8')).excluded ?? []
}

function discoverSources() {
  const files = walk(ROOT, ROOT, [])
  const excluded = new Set(loadExclusions())
  const sources = []
  for (const rel of files) {
    if (!rel.endsWith('.md')) continue
    if (rel.endsWith('.zh.md') || rel.endsWith('.ru.md')) continue
    if (rel.endsWith('.i18n.yaml')) continue
    if (rel.split('/').pop() === 'CLAUDE.md') continue
    if (SKIP_BASENAMES.has(rel.split('/').pop())) continue
    if (isTestArtifact(rel)) continue
    if (isSkillBody(rel)) continue
    if (excluded.has(rel)) continue
    if (SKIP_DIR_PREFIXES.some(prefix => rel.startsWith(prefix))) continue
    if (SKIP_FILES.has(rel)) continue
    sources.push(rel)
  }
  return sources.sort()
}

function loadManifest() {
  if (!existsSync(MANIFEST_PATH)) return { pairs: {} }
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'))
}

function saveManifest(manifest) {
  writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`)
}

function analyze(sourceRel, ruRel, manifestPair) {
  const result = { sourceRel, ruRel, status: 'ok', problems: [] }
  const sourcePath = join(ROOT, sourceRel)
  const ruPath = join(ROOT, ruRel)
  if (!existsSync(ruPath)) {
    result.status = 'missing'
    return result
  }
  if (!existsSync(sourcePath)) {
    result.status = 'orphan'
    result.problems.push(`source disappeared: ${sourceRel}`)
    return result
  }
  const sourceText = readFileSync(sourcePath, 'utf8')
  const ruText = readFileSync(ruPath, 'utf8')
  if (headingDepths(sourceText).join(',') !== headingDepths(ruText).join(',')) {
    result.status = 'structural'
    result.problems.push('heading-depth sequence differs from source')
  }
  const srcFences = fenceSignatures(sourceText)
  const ruFences = fenceSignatures(ruText)
  if (srcFences.length !== ruFences.length || srcFences.some((fence, index) => fence !== ruFences[index])) {
    result.status = 'structural'
    result.problems.push('fenced code blocks differ from source (count, order, info string, or body)')
  }
  if (manifestPair === undefined) {
    result.status = result.problems.length > 0 ? 'structural' : 'unrecorded'
    if (result.problems.length === 0) result.problems.push('no recorded hashes; confirm consistency, then run --write')
    return result
  }
  if (result.problems.length === 0 && manifestPair.source !== sourceRel) {
    result.problems.push(`manifest source is ${manifestPair.source}`)
    result.status = 'outdated'
  }
  if (result.status !== 'structural') {
    const sourceHash = gitBlobHash(sourceText)
    const ruHash = gitBlobHash(ruText)
    if (manifestPair.sourceBlob !== sourceHash || manifestPair.ruBlob !== ruHash) {
      result.status = 'outdated'
      result.problems.push(
        manifestPair.sourceBlob !== sourceHash && manifestPair.ruBlob !== ruHash
          ? 'both sides changed since last confirmation'
          : manifestPair.sourceBlob !== sourceHash
            ? 'English source changed since last confirmation'
            : 'Russian side changed since last confirmation',
      )
    }
  }
  return result
}

function buildStates() {
  const manifest = loadManifest()
  const states = new Map()
  for (const sourceRel of discoverSources()) {
    const ruRel = sourceRel.replace(/\.md$/, '.ru.md')
    states.set(ruRel, analyze(sourceRel, ruRel, manifest.pairs[ruRel]))
  }
  const seenSources = new Set([...states.values()].map(state => state.sourceRel))
  for (const [ruRel, pair] of Object.entries(manifest.pairs)) {
    if (states.has(ruRel) || seenSources.has(pair.source)) continue
    states.set(ruRel, { sourceRel: pair.source, ruRel, status: 'orphan', problems: [`source disappeared: ${pair.source}`] })
  }
  return { manifest, states }
}

function resolveWriteTargets(requested, states) {
  const targets = []
  for (const request of requested) {
    const normalized = request.split('\\').join('/').replace(/^\.\//, '')
    const candidates = [
      normalized.replace(/\.md$/, '.ru.md'),
      `${normalized}.ru.md`,
      `${normalized}.md`.replace(/\.md\.md$/, '.md'),
    ]
    const hit = [...states.keys()].find(key => candidates.includes(key))
      ?? [...states.values()].filter(state => state.sourceRel === normalized).map(state => state.ruRel)[0]
    if (hit === undefined) throw new Error(`no known pair matches "${request}"`)
    targets.push(hit)
  }
  return targets
}

function record(manifest, states, ruRels) {
  for (const ruRel of ruRels) {
    const state = states.get(ruRel)
    if (state === undefined || state.status === 'missing' || state.status === 'orphan') {
      throw new Error(`cannot record ${ruRel}: pair incomplete`)
    }
    if (state.status === 'structural') throw new Error(`cannot record ${ruRel}: ${state.problems.join('; ')}`)
    manifest.pairs[ruRel] = {
      source: state.sourceRel,
      sourceBlob: gitBlobHash(readFileSync(join(ROOT, state.sourceRel), 'utf8')),
      ruBlob: gitBlobHash(readFileSync(join(ROOT, ruRel), 'utf8')),
    }
  }
}

const ORDER = ['ok', 'unrecorded', 'outdated', 'missing', 'orphan', 'structural']

function main() {
  const { manifest, states } = buildStates()

  if (writePairs !== null) {
    const targets = resolveWriteTargets(writePairs, states)
    record(manifest, states, targets)
    saveManifest(manifest)
    console.log(`re-recorded ${targets.length} pair(s):`)
    for (const target of targets) console.log(`  ok       ${target}`)
    return
  }

  const rows = [...states.entries()].sort((left, right) =>
    left[1].status.localeCompare(right[1].status) || left[0].localeCompare(right[0]))
  const counts = Object.fromEntries(ORDER.map(status => [status, 0]))
  for (const [, state] of rows) counts[state.status] += 1

  if (listOnly) {
    for (const [, state] of rows) console.log(`${state.status.padEnd(10)} ${state.ruRel}`)
  } else {
    const interesting = rows.filter(([, state]) => state.status !== 'ok')
    for (const [, state] of interesting) {
      console.log(`${state.status.padEnd(10)} ${state.ruRel}`)
      for (const problem of state.problems) console.log(`           - ${problem}`)
    }
  }

  const summary = ORDER.map(status => `${status}: ${counts[status]}`).join(', ')
  console.log(`\n${summary}`)

  if (process.env.GITHUB_STEP_SUMMARY !== undefined) {
    const lines = [
      '## Russian documentation status', '',
      '| Status | Count |', '|---|---|',
      ...ORDER.map(status => `| ${status} | ${counts[status]} |`), '',
    ]
    const flagged = rows.filter(([, state]) => ['outdated', 'unrecorded', 'orphan', 'structural'].includes(state.status))
    if (flagged.length > 0) {
      lines.push('### Needs attention', '')
      for (const [, state] of flagged) {
        lines.push(`- **${state.status}** \`${state.ruRel}\`${state.problems.length > 0 ? ` — ${state.problems.join('; ')}` : ''}`)
      }
    }
    writeFileSync(process.env.GITHUB_STEP_SUMMARY, `${lines.join('\n')}\n`, { flag: 'a' })
  }

  const broken = counts.orphan + counts.structural
  if (broken > 0) {
    console.error(`\n${broken} pair(s) violate the Russian-layer contract`)
    process.exitCode = 2
  } else if (strict && counts.outdated + counts.unrecorded > 0) {
    console.error('\n--strict: outdated or unconfirmed pairs present')
    process.exitCode = 1
  }
}

main()
